### ISSUE TITLE
Bug regarding colorization of help commands

### ISSUE THREAD

**Issue by brandonywl** [AY2021S1-CS2113-T13-1/tp#105]
Issue occured when using help command on Intellij 2020.2 on Win 10 Pro.

![image](https://user-images.githubusercontent.com/28587601/96824566-abb3c280-1461-11eb-9c87-d2c471e0c1d4.png)

**Comment by Chongjx** [comment]
This is not a bug. Intellji prints white font as black and vice versa. See attached image to change it such that it displays the correct color on intellji

![image](https://user-images.githubusercontent.com/8433829/96824902-84112a00-1462-11eb-9571-87da22219515.png)

**Comment by brandonywl** [comment]
Noted. So for this we should highlight it in the developer guide right?

**Comment by Chongjx** [comment]
Yup!

**Comment by brandonywl** [comment]
Okay thanks for the clarification! Closing this.
