### ISSUE TITLE
[BUG] /del on first line of add-n content

### ISSUE THREAD

**Issue by R-Ramana** [AY2021S1-CS2113-T13-1/tp#118]
See snippets for details on the issue.

![Screenshot_1](https://user-images.githubusercontent.com/54029207/97030459-62629080-1591-11eb-9893-1cead4c3d898.png)

**Comment by Nazryl** [comment]
Its fixed on my side. I havent commited.

**Comment by R-Ramana** [comment]
> Its fixed on my side. I havent commited.

Noted! Feel free to close the issue when you make the PR.
