### ISSUE TITLE
Developer Guide feedback

### ISSUE THREAD

**Issue by leowweixiang** [AY2021S1-CS2113-T13-1/tp#171]
- [x] 2.3 ParserManager: Diagram is not easily viewable from a 14.1" laptop screen. Recommend reducing the number of commands in the diagram; add a "for the full list of commands, see Section 2.4/Appendix"
- [x] 2.3 ParserManager: Since the section header is `ParserManager`, recommend one class diagram that focuses on the `ParserManager`, on top of what you have for Parser/Commands. Unless the `ParserManager` is very trivial
- [x] Sequence diagrams in general: Follow the module's convention of having colons e.g. `:ParserManager`
- [x] 2.4 Commands: In addition to what happens with the respective Commands, recommend adding a one-liner to describe what each command does (from a user-perspective; so that the developer knows what this command specifically does) 

> `AddNoteCommand`
> description of purpose
> 1. Created by the `parserManager`...

- [x] 2.4 Commands: Make `AddNoteCommand`'s sequence diagram consistent with the others (blue background etc)
- [x] 2.4 Commands: Make `PinCommand`'s sequence diagram consistent with the others (`:NotUS` on the left and `:PinCommand` in the center, instead of sequence diagram going left then right)
- [x] 2.5 Notebook: You have multiple overloaded methods with no explanation. Consider reducing to only the main ones that should be used - if you want to include all of them, give a brief explanation of why e.g. there are two `archiveNotes` with different arguments _and_ return values. Same for all other class diagrams
- [x] 2.5 Notebook: You may want to discuss Notes in more detail. What kind of information a `Note` stores, the purpose of it being Taggable etc
- [x] 2.6 Timetable: Recommend going into more detail, since it's mentioned in the high-level architecture diagram. A new developer may want to expand on it and know what interacts with it
- [x] 2.8 Storage: Can talk about when it saves too (currently only at exit?), and draw sequence diagrams of when it loads and saves
- [x] 2.9 User Interface: Only time the `Formatter` shows up, recommend explaining how it is used and works with others. Lack of reference to `InterfaceManager`

**Comment by R-Ramana** [comment]
Last feedback addressed with #210 
Will close this issue.
