### ISSUE TITLE
Potential issue with input formatting error message

### ISSUE THREAD

**Issue by brandonywl** [AY2021S1-CS2113-T13-1/tp#186]
@Chongjx can advise on implementation on other modules if this would affect them? Hard for us to implement a solution for all specifically for indexing though.
![image](https://user-images.githubusercontent.com/28587601/98019558-dd9f2e80-1e3c-11eb-8618-56553da01fe1.png)

**Comment by brandonywl** [comment]
Issue here is no / was provided, so the programme took the entire thing as it's infoDetails[1], thus throwing NumberFormatException and the index format error is shown.

**Comment by Chongjx** [comment]
I think the message shown here is acceptable since the programme interprets the whole thing as the index.

**Comment by brandonywl** [comment]
Ok, then I'll just close this issue
