### ISSUE TITLE
Untag events does not remove the event from the tagMap in TagManager

### ISSUE THREAD

**Issue by Chongjx** [AY2021S1-CS2113-T13-1/tp#199]
For the TagEventCommandTest, untag of event does not work if the event has same start and end time. i.e. noTagEvent = new Event("Default", LocalDateTime.now(), LocalDateTime.now());

Debugged and found the root to be the overriden equal function for Event, occursDuringEvent -> CheckClash. 

There is no issue when the start time and end time is different.

**Comment by brandonywl** [comment]
Closed with PR #200
