### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Chongjx** [AY2021S1-CS2113-T13-1/tp#54]
~~Remove SystemException from Command classes. (AddNoteCommand, DeleteEventCommand) (@Nazryl, @brandonywl)~~
~~Remove NULL_INT from Command (@prachi2023)~~
~~Create COMMAND_SUCCESSFUL_MESSAGE and COMMAND_UNSUCCESSFUL_MESSAGE for respective Command classes (@Nazryl, @brandonywl, @prachi2023, @R-Ramana)~~
~~Toggle function for pinning of notes (@prachi2023)~~
~~Update ViewNoteCommand to print note title and tags (@prachi2023)~~
~~Update prepareListNote to follow the format of other prepare functions (@R-Ramana)~~
~~Change private static final COMMAND_USAGE to public and remove getCommandUsage (@R-Ramana)~~
~~Pass storageManager into Command class (@Chongjx)~~

**Comment by brandonywl** [comment]
Are we done with this issue or do we close it?

**Comment by Chongjx** [comment]
Yup I will close it.
